Changes

diff --git a/runcoms/zshrc b/runcoms/zshrc
--- a/runcoms/zshrc
+++ b/runcoms/zshrc
@@ -5,6 +5,13 @@ if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]
   source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
 fi
 
+#
+# Executes commands at the start of an interactive session.
+#
+# Authors:
+#   Sorin Ionescu <sorin.ionescu@gmail.com>
+#
+
 # Source Prezto.
 if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
   source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
@@ -17,31 +24,59 @@ function cdd {
       then
               cd $1
       fi
-
 }
 compdef '_files -W "$HOME/Development"' cdd
 
+source ~/.aliases
 
-function tableflip {
-  echo "（╯°□°）╯ ┻━┻";
-}
+source <(kubectl completion zsh)
+source <(helm completion zsh)
 
-function dxdd {
-  if pgrep Xcode >/dev/null; then
-    echo "Cannot delete derived data while Xcode is running!"
-  else
-    echo "Deleting `cd ~/Library/Developer/Xcode; pwd`/DerivedData"
-    rm -rf ~/Library/Developer/Xcode/DerivedData
-  fi
-}
+test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
 
-alias be='bundle exec'
-alias home="vcsh dotfiles"
+fpath=(/usr/local/share/zsh-completions $fpath)
 
-# run z script
-. ~/bin/z.sh
+# Enable history
+HISTFILE=${ZDOTDIR:-$HOME}/.zsh_history
+setopt EXTENDED_HISTORY
 
-export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
+# share history across multiple zsh sessions
+setopt SHARE_HISTORY
+
+# append to history
+setopt APPEND_HISTORY
+
+# adds commands as they are typed, not at shell exit
+setopt INC_APPEND_HISTORY
+
+# expire duplicates first
+setopt HIST_EXPIRE_DUPS_FIRST
+
+# do not store duplications
+setopt HIST_IGNORE_DUPS
+
+#ignore duplicates when searching
+setopt HIST_FIND_NO_DUPS
+
+# removes blank lines from history
+setopt HIST_REDUCE_BLANKS
+
+# source MFA script
+source ~/mfa/alias.sh
 
 # To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
 [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
+
+function cpr() {
+    if ! [[ "$(git remote get-url origin)" =~ ":(.*)/(.*).git" ]]; then
+        echo "Could not find correct remote."
+        exit 1
+    fi
+
+    organization=$(echo $match | cut -d" " -f1)
+    repository=$(echo $match | cut -d" " -f2)
+    currentBranch=$(git rev-parse --abbrev-ref HEAD)
+    target=$1
+
+    open "https://bitbucket.org/$organization/$repository/pull-requests/new?source=$currentBranch&dest=$target"
+}
